Gestion de l'habilitation par email via l'API de dépôt
BaseAdresseNationale/api-bal pull request #300
Opened 2021-11-23 11:04 UTC by tmerlier

## Description
Permet la gestion de l'habilitation par email d'une Base Adresse Locale via l'[API dépôt](https://github.com/BaseAdresseNationale/api-depot).

Les informations de l'habilitation sont ajoutées à `bases_locales.habilitation`.

### Modèle habilitation
```
habilitation:
    _id
    strategyType
    status
    createdAt
    updatedAt
    expiresAt
```

### Nouvelles routes
- [**POST**] `/bases-locales/:baseLocaleId/communes/:codeCommune/authentification`
  - Création d'une habilitation
- [**POST**] `/bases-locales/:baseLocaleId/communes/:codeCommune/authentification/email/send-pin-code`
  - Choix de la strategy de d'habilitation
  - envoi du code par email
- [**POST**] `/bases-locales/:baseLocaleId/communes/:codeCommune/authentification/email/validate-pin-code`
  - Validation du code

2021-11-23 11:29 UTC, jdesboeufs requested changes

2021-11-23 11:29 UTC, jdesboeufs commented on .env.sample
> +API_BAN_TOKEN=xxxxxxxxxxxxxxx
API_DEPOT_*
Il y a 50 API "BAN" ne mélangeons pas tout.

2021-11-23 11:29 UTC, jdesboeufs commented on .env.sample
> +API_BAN_URL=https://api-depot.adresse.data.gouv.fr/
L'URL de base est https://plateforme.adresse.data.gouv.fr/api-depot(-demo)
Par convention on ne met pas le dernier `/`

2021-11-23 11:29 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const fieldsToOmit = ['client', 'codeCommune', 'emailCommune', 'strategy']
Il vaut mieux dans ce cas utiliser `pick` et sélectionner ce qu'on prend.

2021-11-23 11:29 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const fieldsToOmit = ['client', 'codeCommune', 'emailCommune', 'strategy']
Et dans ce cas tu peux juste destructurer et recopier les clés plutôt qu'utiliser une fonction tierce.

2021-11-23 11:29 UTC, jdesboeufs commented on lib/util/api-depot.js
> +const API_BAN_URL = process.env.API_BAN_URL || 'https://api-depot.adresse.data.gouv.fr/'
Renommer la variable d'environnement et modifier la valeur par défaut.

2021-11-23 11:29 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const habilitation = createHabilitation(codeCommune)
await

2021-11-23 11:29 UTC, jdesboeufs commented on lib/models/base-locale.js
> +function formatHabilitation(habilitation) {
format est inadapté ici. On s'attend à récupérer une valeur affichable.

2021-11-23 11:29 UTC, jdesboeufs commented on lib/models/base-locale.js
> +function formatHabilitation(habilitation) {
Tu peux utiliser prepareHabilitation

2021-11-23 11:29 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  return value
C'est un peu exagéré de retourner la BAL entière pour une opération de ce genre.
Un updateOne aurait probablement été plus efficace, et tu retournes juste l'entrée habilitation.

2021-11-23 11:29 UTC, jdesboeufs commented on lib/models/base-locale.js
> +function askAuthentificationCode(habilitationId) {
ça mange pas de pain de la déclarer async

2021-11-23 11:29 UTC, jdesboeufs commented on lib/models/base-locale.js
> +function askAuthentificationCode(habilitationId) {
Ce code n'a plus rien à faire dans le modèle BAL puisqu'il n'utilise pas l'`_id`. C'est un helper `habilitation`.

2021-11-23 11:29 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const habilitation = validatePinCode(baseLocale.habilitation._id, code)
Pareil, helper. Ça va dans `lib/habilitations` (tu peux d'ailleurs rapatrier ton util qui n'a pas grand chose d'un util :p)

2021-11-23 11:29 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const habilitation = validatePinCode(baseLocale.habilitation._id, code)
Si pas d'habilitation en cours => 💥

2021-11-23 11:29 UTC, jdesboeufs commented on lib/models/base-locale.js
> +    const {value} = await mongo.db.collection('bases_locales').findOneAndUpdate(
Comme plus haut, le findOneAndUpdate est sujet à discussion.

2021-11-23 11:29 UTC, jdesboeufs commented on lib/models/base-locale.js
> +    if (habilitation.emailCommune) {
Alors pour moi c'est à l'API de dépôt d'envoyer le mail.

2021-11-23 11:29 UTC, jdesboeufs commented on lib/models/base-locale.js
> +      const email = createPublicationEmail({baseLocale})
Publication email ??

2021-11-23 11:29 UTC, jdesboeufs commented on lib/routes/index.js
> +      return res.status(403).send({code: 403, message: 'Cette Base Adresse Locale possède déjà une habilitation'})
Il faut tester si elle est active (non expirée).

2021-11-23 11:29 UTC, jdesboeufs commented on lib/routes/index.js
> +      const {code, message} = JSON.parse(error.response.body)
JSON.parse inutile.

2021-11-23 11:29 UTC, jdesboeufs commented on lib/routes/index.js
> +    res.sendStatus(200)
Tu ne peux pas renvoyer juste le statut si tu renvoies des erreurs JSON.
Il faut renvoyer du JSON.

2021-11-23 13:33 UTC, tmerlier commented on lib/models/base-locale.js
> +      const email = createPublicationEmail({baseLocale})
Un email prévenant que la Base Adresse Locale a bien été publiée.

2021-11-23 16:49 UTC, tmerlier commented on lib/models/base-locale.js
> +      const email = createPublicationEmail({baseLocale})
Je mélange la publication et l'habilitation… Au temps pour moi je retire.

2021-11-23 17:00 UTC, tmerlier commented on lib/routes/index.js
> +    res.sendStatus(200)
En cas d'erreur, un `return` est utilisé ligne 205 afin de stopper l'exécution du code et envoyé l'erreur JSON.

2021-11-24 21:11 UTC, jdesboeufs requested changes
Bon en vrai je pense qu'il faudrait stocker les habilitations dans une collection :D

2021-11-24 21:11 UTC, jdesboeufs commented on lib/__tests__/habilitations.js
> +test('prepare habilitation whitout strategy', t => {
without please

2021-11-24 21:11 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const {value} = await mongo.db.collection('bases_locales').updateOne(
Désolé ça ne s'utilise pas comme ça.

2021-11-24 21:11 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const {value} = await mongo.db.collection('bases_locales').updateOne(
Désolé ça ne s'utilise pas comme ça.

2021-11-24 21:11 UTC, jdesboeufs commented on lib/routes/index.js
> +    } catch (error) {
Je comprends pas à quoi sert cette partie. On a déjà un errorHandler.

2021-11-25 22:54 UTC, jdesboeufs requested changes

2021-11-25 22:54 UTC, jdesboeufs commented on lib/models/base-locale.js
> +async function updateHabilitation(baseLocale, habilitation) {
Les deux fonctions sont presque identiques. Optimisons :)

2021-11-25 22:54 UTC, jdesboeufs commented on lib/routes/__tests__/base-locale.js
> +test.serial('create an habilitation for a baseLocale', async t => {
Vue la taille du fichier je pense que tu peux créer un fichier séparé pour cette partie des tests.

2021-11-25 22:54 UTC, jdesboeufs commented on lib/habilitations.js
> +    _id,
parseObjectId

2021-11-25 22:54 UTC, jdesboeufs commented on lib/habilitations.js
> +    createdAt,
new Date pour les 3, si défini

2021-11-25 22:54 UTC, jdesboeufs commented on lib/routes/index.js
> +      const expiresAt = new Date(req.baseLocale.habilitation.expiresAt)
Inutile de caster on l'aura fait dans prepareHabilitation

2021-11-25 22:54 UTC, jdesboeufs commented on lib/routes/index.js
> +      return res.status(412).send({code: 412, message: 'Aucune demande d’habilitation en attente'})
Ça se factorise avec un middleware tout ça.

2021-11-26 15:26 UTC, jdesboeufs requested changes

2021-11-26 15:26 UTC, jdesboeufs commented on lib/habilitations.js
> +const API_DEPOT_URL = process.env.API_DEPOT_URL || 'https://plateforme.adresse.data.gouv.fr/api-depot(-demo)'
(-demo) c'est une valeur qui ne fonctionnera jamais ;)

2021-11-26 15:26 UTC, jdesboeufs commented on lib/habilitations.js
> +  if (body.validated === false) {
Tu ne conserves pas la valeur remainingAttempts du coup ?
Si j'atteinds 0, comme je le sais ? Comment je relance un mail ?

2021-11-26 15:26 UTC, jdesboeufs commented on lib/routes/index.js
> +    return res.status(412).send({code: 412, message: 'Aucune demande d’habilitation en attente'})
Tu penses qu'une mairie comprendrai cette phrase ? :)

2021-11-26 15:26 UTC, jdesboeufs commented on lib/routes/index.js
> +      if (status === 'accepted' && expiresAt > now) {
Else => On tombe dans le cas en dessous. Est-ce attendu de réinitialiser l'habilitation ?

2021-11-26 15:26 UTC, jdesboeufs commented on lib/routes/index.js
> +    const {body} = await sendPinCode(req.baseLocale.habilitation._id)
À quel moment tu contrôle qu'on a la bonne stratégie ? Demain on aura aussi FC.

2021-11-26 15:41 UTC, tmerlier commented on lib/routes/index.js
> +      if (status === 'accepted' && expiresAt > now) {
Je propose qu'on commence comme ça et qu'on permette le renouvellement d'habilitation quand on aura passer l'habilitation de la BAL en object d'habilitations.

2021-11-26 15:41 UTC, tmerlier commented on lib/routes/index.js
> +    const {body} = await sendPinCode(req.baseLocale.habilitation._id)
La route est `/authentication/email`. Je pensais ajouter `/authentication/france-connect` ensuite.

2021-11-26 15:44 UTC, tmerlier commented on lib/habilitations.js
> +  if (body.validated === false) {
Le message contenant le nombre d'essai restant est renvoyé par l'api-dépôt et affiché à l'utilisateur dans le front. On peut faire évoluer l'api-dépôt pour qu'elle renvoi `remainingAttempts` et gérer ça directement.

L'utilisateur peut redemander un mail depuis l'interface, cela a pour effet de rappeler la route `authentication/email/send-pin-code`.

2021-11-26 15:45 UTC, tmerlier commented on lib/routes/index.js
> +    return res.status(412).send({code: 412, message: 'Aucune demande d’habilitation en attente'})
Les mairies ne sont normalement pas sensées voir ce message si le front fait bien son travail.

2021-11-26 15:50 UTC, tmerlier commented on lib/routes/index.js
> +      if (status === 'accepted' && expiresAt > now) {
Sinon un utilisateur que recommencerai un demande d'habilitation sans la terminer écraserait celle qui est active.

2021-11-26 22:24 UTC, jdesboeufs approved these changes

2021-12-14 10:29 UTC, merged