Ajout de nouvelles métriques destinées au tableau de bord
BaseAdresseNationale/api-bal pull request #307
Opened 2022-01-21 15:01 UTC by cedric-famibelle-pronzola

Remplace la PR #304 

Concerne les BAL publiée uniquement :

- Nombre de numéros certifiés
- Nombre de voies
- Nombre de lieux-dits

## ⚠️  Liée à la PR [mes-adresses #481](https://github.com/BaseAdresseNationale/mes-adresses/pull/481)

## *edit 25/01* 
- Modification de la requête mongo
- Ajout de `nbNumeros`
- La route `/stats/bases-locales` devient `/stats`

## *edit 02/02*
- Ajout d'un cache pour la route `/stats`

2022-01-24 15:28 UTC, GllmR approved these changes

2022-01-24 16:24 UTC, jdesboeufs requested changes

2022-01-24 16:24 UTC, jdesboeufs commented on lib/models/base-locale.js
> +    nbNumerosCertifies
Tu peux ajouter aussi nbNumeros pour être complet

2022-01-24 16:24 UTC, jdesboeufs commented on lib/models/base-locale.js
> +  const nbVoies = await mongo.db.collection('voies').find({_bal: {$in: publishedBasesLocalesIds.map(({_id}) => mongo.parseObjectID(_id))}}).count()
Par cohérence avec le reste du code BAL tu peux utiliser directement `.count(...)` plutôt que `.find(...).count()`

2022-01-24 16:24 UTC, jdesboeufs commented on lib/routes/stats.js
> +app.route('/bases-locales')
`/stats` plutôt ?

2022-01-25 09:48 UTC, jdesboeufs requested changes

2022-01-25 09:48 UTC, jdesboeufs commented on lib/routes/stats.js
> +        const expandedBal = await BaseLocale.expandModel(bal)
C'est beaucoup trop lourd de faire ça malheureusement. Ça fait 4x nb BAL publiées x requêtes count. C'est énorme.

2022-01-25 09:48 UTC, jdesboeufs commented on lib/routes/stats.js
> +        const expandedBal = await BaseLocale.expandModel(bal)
Je te suggère de mettre en place une fonction "computeStats" qui prend en entrée une query, et qui ensuite calcule les statistiques sur cette requête, avec des appels `aggregate`.

2022-01-27 20:19 UTC, jdesboeufs commented
@cedric-famibelle-pronzola t'as pu faire les corrections ?

2022-01-28 05:12 UTC, cedric-famibelle-pronzola commented
> @cedric-famibelle-pronzola t'as pu faire les corrections ?

@jdesboeufs je pensais qu'on devait attendre que la branche api-depot soit mergée

2022-02-01 10:30 UTC, jdesboeufs commented
Non il n'y a pas de lien.

2022-02-01 11:19 UTC, cedric-famibelle-pronzola commented
> Non il n'y a pas de lien.

ok je m'en occupe

2022-02-01 19:53 UTC, jdesboeufs commented on lib/models/base-locale.js
> +async function expandModel(baseLocale) {
À quoi sert expandModel ?

2022-02-02 12:24 UTC, jdesboeufs approved these changes

2022-02-02 12:58 UTC, jdesboeufs approved these changes

2022-02-02 12:59 UTC, merged